excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://kwandanu.github.io
title: Cultist A Day
email: craigbuyer553@hotmail.com
author: Sploor
description: Painting my Warhammer 40k Chaos Space Marine Army.
paginate: 3
google_analytics: 